version: '5.35'

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    networks:
      - backend
    restart: always

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    networks:
      - backend
    restart: always

  client-gateway:
    container_name: client-gateway
    build: ./
    ports:
      - ${NEST_PORT_GATEWAY}:3000
    volumes:
      - ./apps/challenge-dfl/src:/usr/src/app/src
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: npm run start:main
    environment:
      - NEST_LIST_CURRENCY=USD,EUR,CAD,UER
      - NEST_PORT_GATEWAY=3000
      - NEST_PORT_REDIS=6379
      - NEST_HOST_REDIS=redis
      - APP_JWT_SECRET=sasd111qsSaskkjshehyyluuwolsjush**77197hbbaggt
      - NEST_HOST_CURRENCY=currency-ms
      - NEST_HOST_TRANSACTION=transaction-ms
    networks:
      - backend
    depends_on:
      - redis
      - mongo
      - currency-ms
      - transaction-ms

  currency-ms:
    container_name: currency-ms
    build: ./
    ports:
      - ${NEST_PORT_MS_CURRENCY}:3001
    volumes:
      - ./apps/currency-ms/src:/usr/src/app/src
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: npm run start:currency-ms
    environment:
      - NEST_PORT_MS_CURRENCY=3001
      - NEST_PORT_REDIS=6379
      - NEST_HOST_REDIS=redis
      - NEST_BASE_URL_EXCHANGE_API=https://concurso.dofleini.com/exchange-rate/api/latest
      - NEST_BASE_CURRENCY=USD
      - NEST_HOST_CURRENCY=currency-ms
      - NEST_LIST_CURRENCY=USD,EUR,CAD,UER
    networks:
      - backend
    depends_on:
      - redis
      - mongo

  transaction-ms:
    container_name: transaction-ms
    build: ./
    ports:
      - ${NEST_PORT_MS_TRANSACTION}:3002
    volumes:
      - ./apps/transaction-ms/src:/usr/src/app/src
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: npm run start:transaction-ms
    environment:
      - NEST_PORT_MS_TRANSACTION=3002
      - NEST_PORT_REDIS=6379
      - NEST_HOST_REDIS=redis
      - NEST_HOST_TRANSACTION=transaction-ms
    networks:
      - backend
    depends_on:
      - redis
      - mongo

networks:
  backend:
    driver: bridge

volumes:
  redis:
    driver: local
  mongo: { }
