export const ERROR_CODE = {
  INVALID_CURRENCY: 'INVALID_CURRENCY',
  DUPLICATED_TRANSACTION: 'DUPLICATED_TRANSACTION',
  INVALID_TRANSACTION_TYPE: 'INVALID_TRANSACTION_TYPE',
  MISSING_REQUIRED_FIELDS: 'MISSING_REQUIRED_FIELDS',
};
