export const ERROR_CODE = {
  INVALID_CURRENCY: 'INVALID_CURRENCY',
  DUPLICATED_TRANSACTION: 'DUPLICATED_TRANSACTION',
  INVALID_TRANSACTION_TYPE: 'INVALID_TRANSACTION_TYPE',
  MISSING_REQUIRED_FIELDS: 'MISSING_REQUIRED_FIELDS',
  TRANSACTION_TYPE_NOT_FOUND: '001',
  TRANSACTION_NOT_CREATED: '002',
  TRANSACTION_NOT_REMOVE: '003',
  TRANSACTION_TYPE_NOT_CREATED: '004',
  TRANSACTION_TYPE_NOT_UPDATED: '005',
  TRANSACTION_TYPE_NOT_REMOVE: '006',
};
